
const pedidosBD = [
        {
            id: 1,
            cliente: 'Verdulería Santa Fe',
            descripcion: '10 kg de zanahoria, 8 kg de papa, 5 kg de cebolla, 3 lechugas, 2 kg de tomates cherry, 5 pepinos, 3 kg de pimientos rojos, 2 kg de pimientos verdes, 4 kg de calabaza, 6 manzanas, 10 naranjas.',
            precio: 10000,
            precioAbonado: 5000,
            precioRestante: 5000,
            fecha: "20/09/2025",
            estado: 'Impago',
        },
        {
            id: 2,
            cliente: 'Almacen Verona',
            descripcion: '20 kg de manzana, 15 kg de pera, 10 kg de banana, 5 kg de limones',
            precio: 25000,
            precioAbonado: 25000,
            precioRestante: 0,
            fecha: "20/09/2025",
            estado: 'Pago',
        },
        {
            id: 3,
            cliente: 'Supermercado Chino',
            descripcion: '5 kg de zapallo, 10 kg de batata, 6 kg de cebolla de verdeo, 4 lechugas',
            precio: 18000,
            precioAbonado: 9000,
            precioRestante: 9000,
            fecha: "22/09/2025",
            estado: 'Impago',
        },
        {
            id: 4,
            cliente: 'Distribuidora Santa Fe',
            descripcion: 'Pedido semanal: 12 kg de papa, 8 kg de cebolla, 5 lechugas, 2 kg de pepino, 3 kg de pimientos, 4 kg de zapallo, 6 kg de zanahoria, 5 kg de tomate, 2 kg de calabaza, 10 manzanas, 5 naranjas.',
            precio: 12000,
            precioAbonado: 12000,
            precioRestante: 0,
            fecha: "23/09/2025",
            estado: 'Pago',
        },
        {
            id: 5,
            cliente: 'Mercado Central',
            descripcion: 'Pedido semanal: 15 kg de banana, 20 kg de manzana, 10 kg de naranja, 8 kg de pera, 5 kg de limón, 2 kg de mandarina, 6 kg de lechuga, 3 kg de acelga, 4 kg de zapallo, 2 kg de calabaza.',
            precio: 27000,
            precioAbonado: 13500,
            precioRestante: 13500,
            fecha: "24/09/2025",
            estado: 'Impago',
        },
        {
            id: 6,
            cliente: 'Verdulería El Bosque',
            descripcion: 'Pedido semanal: 10 kg de zapallo, 6 kg de batata, 8 lechugas, 4 kg de cebolla de verdeo, 3 kg de pepino, 2 kg de pimientos, 5 kg de zanahoria, 4 kg de tomate, 6 kg de manzana, 5 kg de pera, 3 kg de banana.',
            precio: 20000,
            precioAbonado: 20000,
            precioRestante: 0,
            fecha: "25/09/2025",
            estado: 'Pago',
        },
        {
            id: 7,
            cliente: 'Distribuidora Santa Fe',
            descripcion: 'Pedido semanal: 8 kg de zanahoria, 10 kg de papa, 3 kg de tomates, 2 lechugas, 1 kg de pepinos, 2 kg de pimientos, 5 kg de calabaza, 4 kg de zapallo, 6 manzanas, 3 naranjas, 2 kg de limones.',
            precio: 11000,
            precioAbonado: 5500,
            precioRestante: 5500,
            fecha: "26/09/2025",
            estado: 'Impago',
        },
        {
            id: 8,
            cliente: 'Mercado Central',
            descripcion: 'Pedido semanal: 25 kg de pera, 15 kg de manzana, 10 kg de banana, 5 kg de limón, 6 kg de naranja, 4 kg de mandarina, 8 kg de lechuga, 5 kg de tomate, 3 kg de pepino, 2 kg de pimientos, 1 kg de rúcula.',
            precio: 30000,
            precioAbonado: 30000,
            precioRestante: 0,
            fecha: "27/09/2025",
            estado: 'Pago',
        },
        {
            id: 9,
            cliente: 'Verdulería El Bosque',
            descripcion: 'Pedido semanal: 6 kg de zapallo, 5 kg de batata, 3 lechugas, 2 kg de cebolla de verdeo, 1 kg de pepino, 1 kg de pimientos, 3 kg de zanahoria, 2 kg de tomate, 4 kg de manzana, 2 kg de pera, 1 kg de banana.',
            precio: 15000,
            precioAbonado: 7500,
            precioRestante: 7500,
            fecha: "28/09/2025",
            estado: 'Impago',
        },
        {
            id: 10,
            cliente: 'Distribuidora Santa Fe',
            descripcion: 'Pedido semanal: 15 kg de papa, 10 kg de cebolla, 5 lechugas, 3 kg de pepino, 2 kg de pimientos, 4 kg de zapallo, 6 kg de zanahoria, 5 kg de tomate, 2 kg de calabaza, 10 manzanas, 5 naranjas.',
            precio: 14000,
            precioAbonado: 14000,
            precioRestante: 0,
            fecha: "29/09/2025",
            estado: 'Pago',
        }
    ]

export default pedidosBD